# dataSource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db
    username: root
    password: admin123
  main:
    banner-mode: off
# mp日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      #      设置自增算法
      id-type: assign_id
      #      设置表名前缀
      table-prefix: tbl_
      #      标记逻辑删除的字段
      logic-delete-field: deleted
      #      未删除的标记
      logic-not-delete-value: 0
      #      删除的标记
      logic-delete-value: 1

